### ISSUE TITLE
Create a bash script to ease the launch process

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/vagrant#1]
Hello,

could it be possible to have a local script that asks questions interactively ? This way we don't have to remember every argument and syntax, we just launch the script and answer it.

Thanks !

**Comment by PierreRambaud** [comment]
Files `run.sh` and `run.bat` are now available, Tell me if everything is ok for you :)

**Comment by SimonGrn** [comment]
Perfect, thanks a lot :)
