### ISSUE TITLE
Add module install

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/vagrant#2]
In order to be able to test the PR of the modules, we need an update of the vagrant VM : 

How does QA tests modules ? Here is the answer from our doc (in french, sorry)

> Pour tester une PR sur un module natif il faut (via la console) se rendre dans le dossier modules :
> `cd modules`
> 
> Il faut ensuite supprimer le modules présent :
> `rm -rf nom_du_module`
> 
> Cloner le repo du module (cliquer sur le nom du module, puis sur le bouton “Clone or download”, et copier le lien proposé) :
> `git clone git@github.com:PrestaShop/nom_du_module.git`
> 
> Aller dans le dossier du module :
> `cd nom_du_module`
> 
> Et récupérer la PR à tester :
> `git prc origin numéro_de_la_pr nom_de_la_branche`
> 
> C’est le même principe que pour les PRs du core sauf que la branche est soit dev soit master et la branche courante est origin et non presta
> Se rendre sur le Back office et réinitialiser le module afin d’être sûr que les changement sont appliqués.

Sometimes, there is a need for a Module's PR and a Branch's PR to be installed on same time, but it's pretty rare, so maybe this use case is not useful right now.

**Comment by PierreRambaud** [comment]
First part done.
I need to switch to Windows to create the install-modules.bat script :)

**Comment by PierreRambaud** [comment]
Should be ok now :)
