### ISSUE TITLE
Add support for shop-creator

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/vagrant#3]
Could it be possible to add data from [shop-creator](https://github.com/PrestaShop/prestashop-shop-creator) when launching the VM ?
By using pregenerated fixtures or generating them at runtime, and adding the possibility to choose the size of the sample (roughly, something like 50, 500, 5k).

**Comment by PierreRambaud** [comment]
I need the exact detail of what you need and how you want to use it, and everything is possible.

**Comment by SimonGrn** [comment]
I would like to be able to specify a number of data I want to be inserted when the shop is installed.
- choose a number of data (with preset numbers like 50, 500, 5000)
- launch [shop-creator](https://github.com/PrestaShop/prestashop-shop-creator) to generate these data
- copy the generated files in the correct place (`/install/fixtures/fashion`)

When the shop is installed it will automatically take these data into account and populate the shop with them.

**Comment by PierreRambaud** [comment]
Running shop-creator in the virtual machine is a risk, i'm not even able to do it on my computer when I request more than 500 products :joy:

**Comment by SimonGrn** [comment]
Aww damn. Maybe limit to 50, 100, 250 ?
250 products/orders/customers seems a lot already

**Comment by PierreRambaud** [comment]
If the script is execute on the machine, the limit is maybe 50, and it will take something more than 10 minutes :sweat_smile:

**Comment by SimonGrn** [comment]
OK, we forget this. That's a shame because it would be very beneficial to have more datasets.

**Comment by PierreRambaud** [comment]
If we prepare files it's ok and commit them in this repository, it's ok. But we can't do it on the virtual machine

**Comment by SimonGrn** [comment]
Problem is, files might be different for every version and we can't prepare a dataset for every branch and/or PR...

**Comment by PierreRambaud** [comment]
It should work, there is no option on shop-creator to determine which version of PS you're using.

**Comment by SimonGrn** [comment]
Oh OK, that's very interesting, so we could prepare a few files and commit them, and you could add an option to copy a dataset in the correct folder before installing it ?

**Comment by PierreRambaud** [comment]
Of course, I can do everything for you :heart:

**Comment by SimonGrn** [comment]
So, it took almost 3 hours but I have a dataset :tada: 
Here are the settings I used:
![image](https://user-images.githubusercontent.com/49909275/82810031-c1f72b80-9e8d-11ea-9995-f90f27a2f965.png)

What do you think ? Could this be added ? Maybe only one setting, like "do you want more dummy data ?" and we add this dataset dynamically ?
That's 243Mo of data.

**Comment by PierreRambaud** [comment]
You can create a pull request to add this dataset, I think it's not a problem. But 243Mo of data :scream:

**Comment by SimonGrn** [comment]
That's 236Mo of images for products tho, so I guess I'll relaunch it but I won't let 100 images per product, more like 3 or 4.
Once finished I'll create a PR.

**Comment by MatShir** [comment]
A :heart:  is the only reward I can offer you to help you achieve this PR.

**Comment by SimonGrn** [comment]
The [PR](https://github.com/PrestaShop/vagrant/pull/6) has actually been merged ! I close this issue.
