### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gouz** [PrestaShop/vagrant#5]
Hi, when I'm trying your solution I got this errors : 

Fatal error: Uncaught Exception: file_get_contents_curl failed to download https://i18n.prestashop.com/translations/1.7.7.0/fr-FR/fr-FR.zip : (error code 28) Resolving timed out after 5029 milliseconds in /var/www/html/prestashop/classes/Tools.php on line 2193

Same error with "en" language.

P.S. : I'm on Win10

Best regards

**Comment by PierreRambaud** [comment]
Hi and  thanks for your feedback.
This is because you have latencies when downloading the translations file. This is a know issue with PrestaShop.
Can you try again?

**Comment by gouz** [comment]
same, is-it possible to raise the curl_timeout ?

**Comment by PierreRambaud** [comment]
How much time does it take for you to download this file manually?

**Comment by gouz** [comment]
1.1s

**Comment by PierreRambaud** [comment]
Weird, really weird, do you have some network limitation on your virtual machine? :thinking:

**Comment by gouz** [comment]
nope, all installation scripts (prepare_apt) work, just the install of prestashop
I try on others boxes same bugs. all good with laragon, so you can close the issue

**Comment by PierreRambaud** [comment]
Thanks a lot, we will do our best to fix the issue on the Core project!
